configuration: Release
platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build: nuget.exe restore
after_build: nuget.exe pack StackExchange.Adzerk/StackExchange.Adzerk.csproj -properties Configuration=Release

artifacts:
- path: 'StackExchange.Adzerk.*.nupkg'
  name: StackExchange.Adzerk
