configuration: Release
platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build: nuget.exe restore
build:
  project: StackExchange.Adzerk/StackExchange.Adzerk.csproj
  publish_nuget: true

deploy:
- provider: NuGet
  api_key:
    secure: BUsLevk5w2SaTOUbPd6mTgPrIQ3nFJ8oUH6RSr4aMidhBWo11gSl5v37Lk1vMX7m
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
