configuration: Release
platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build: nuget.exe restore
build:
  project: StackExchange.Adzerk/StackExchange.Adzerk.csproj
  publish_nuget: true
